### ISSUE TITLE
Hal papers not considered as open-access in BASE

### ISSUE THREAD

**Issue by monperrus** [CCSDForge/HAL#8]
**Problem:** I realize that most Hal papers are not tagged as "open-access" by BASE (Bielefeld Academic Search Engine),  while they all contain the PDF.

For instance, this one is not flagged as open-access
<https://www.base-search.net/Record/9cf2e4cfc89276305ebc545ecee3d7dd370fa4466376d9cd258c855f0e764aa2/>

While the PDF is on Hal <http://hal.archives-ouvertes.fr/docs/01/05/45/49/PDF/essay-automatic-repair.pdf>

**Possible solutions:** According to BASE team (private communication), there are solutions:

* add a "license" field in the OAI interface of HAL, it it contains a CC license, the record is considered open-access
* add a "rights" field  in the OAI interface of HAL, it contains the term "open access" , the record is considered open-access
* to provide a special "OA set" in the HAL OAI interface, and every document has to contain the name of the set in the "setSpec" metadata field.

**Comment by monperrus** [comment]
Cross-linking the corresponding CCSD Bug report: <http://mantis.ccsd.cnrs.fr/view.php?id=2286>

**Comment by nemobis** [comment]
I was discussing about this just one day before your report with a person involved in HAL and I agree a software solution should be possible. There are plenty of metadata options, hopefully the developers can implement one of them (of course your suggestions are better than mine because they were confirmed with BASE).

----

AM, 25/10/2017 17:38:
> It seems that BASE considers a deposit is in open access  only if a 
> licence is mentioned in the metadata. That is what we understand when we 
> investigate this question : this can explain the difference of numbers. 
> HAL proposes this metadata only since october 2014 and it is not a 
> required field.
> 
> All files in HAL are open access, except some of them that are under 
> embargo.

Thanks. If I understand <https://www.base-search.net/about/en/faq_oai.php> correctly, you would "only" need to code HAL so that it adds a tag like

```<dc:rights>http://purl.org/eprint/accessRights/OpenAccess</dc:rights>```

when the full text is available without embargo but doesn't carry license information. Or if you want to use a license-like URI, I think <http://rightsstatements.org/page/InC-EDU/1.0/> could be appropriate. RightsStatements is pushed by DPLA and Europeana so I bet BASE could agree to support it.

**Comment by monperrus** [comment]
Correct. When the full text is available without embargo, even a very simple tag like this would be fine (confirmed by BASE team)

    <dc:rights>open access</dc:rights>

(Note that `dc:rights` does not have to contain a specific license, see https://www.openarchives.org/OAI/openarchivesprotocol.html)

**Comment by monperrus** [comment]
FYI, HAL has added `<dc:rights>info:eu-repo/semantics/OpenAccess</dc:rights>` in OAI-PMH.

**Comment by lfarhi** [comment]
Oui, il y a eu une nouvelle version jeudi dernier. Par contre, attention, je ne suis pas sûre que tous les documents aient été réindexés par Solr. A priori, une réindexation complète sera lancée cette semaine et <dc:rights> sera ajouté partout.

**Comment by monperrus** [comment]
super, merci !
